#! /bin/sh

sxhkd &
compton &
nitrogen --restore &

$HOME/.config/polybar/launch.sh

bspc monitor -d one two three four five six

bspc config border_width         2
bspc config window_gap           6
bspc config top_padding		 4
bspc config bottom_padding 	 24
bspc config left_padding 	 4
bspc config right_padding 	 4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
